import type { Metadata } from "next";
import { Noto_Sans_KR } from "next/font/google";
import "./globals.css";

const notoSans = Noto_Sans_KR({
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "R.chive Prototype",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={notoSans.className}>
				<main className="w-full h-[calc(100dvh)] flex overflow-auto justify-center">
					<div className="w-full max-w-[425px] h-full">{children}</div>
				</main>
			</body>
		</html>
	);
}
